### ISSUE TITLE
[Critical bug] WGEF breaks WG's protection

### ISSUE THREAD

**Issue by stonar96** [aromaa/WorldGuardExtraFlagsPlugin#152]
In my opinion this is a very critical bug, because WGEF breaks WG's protection by just installing the plugin (not even using any features).

**The setup:** Install WG and add the following regions:
```
regions:
    inner:
        min: {x: -16, y: 0, z: -16}
        max: {x: 15, y: 255, z: 15}
        members: {}
        flags: {}
        owners:
            unique-ids: [your-uuid]
        type: cuboid
        priority: 1
    outer:
        min: {x: -32, y: 0, z: -32}
        max: {x: 31, y: 255, z: 31}
        members: {}
        flags: {}
        owners: {}
        type: cuboid
        priority: 0

```
Make sure you are not op or have any special permissions. You can build in the inner region. Place a sapling at the edge inside of the inner region and use bone meal to grow the tree. Since you can't build in the outer region, the tree won't grow out of the inner region, as expected.

**The issue:** Now install WGEF and do the exact same thing in-game. The tree will grow outside although it shoudn't.

**Versions:**
WGEF: 4.1.4
WG: 7.0.4
Server: git-Paper-318 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
